In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv('https://raw.githubusercontent.com/iRavshan/pro_data_scientist/main/datasets/police.csv')

In [62]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

# **Ustunlarni qayta nomlash**

In [63]:
df.rename(columns=str.upper)

,STOP_DATE,STOP_TIME,COUNTY_NAME,DRIVER_GENDER,DRIVER_AGE_RAW,DRIVER_AGE,DRIVER_RACE,VIOLATION_RAW,VIOLATION,SEARCH_CONDUCTED,SEARCH_TYPE,STOP_OUTCOME,IS_ARRESTED,STOP_DURATION,DRUGS_RELATED_STOP
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,12/31/2015,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,12/31/2015,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,12/31/2015,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,12/31/2015,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,12/31/2015,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [64]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [65]:
df.rename(columns={'county_name': 'county', 'drugs_related_stop': 'drugs_related'}, inplace=True)

In [66]:
df.columns

Index(['stop_date', 'stop_time', 'county', 'driver_gender', 'driver_age_raw',
       'driver_age', 'driver_race', 'violation_raw', 'violation',
       'search_conducted', 'search_type', 'stop_outcome', 'is_arrested',
       'stop_duration', 'drugs_related'],
      dtype='object')

# **Qiymatlarga ishlov berish**

`replace` funksiyasi

In [67]:
df.replace(['M', 'F'], ['Erkak', 'Ayol'], inplace=True)

In [68]:
df.head()

,stop_date,stop_time,county,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related
0,1/2/2005,1:55,NaN,Erkak,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,Erkak,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,Erkak,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,Erkak,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,Ayol,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [69]:
df['driver_gender'].unique()

array(['Erkak', 'Ayol', nan], dtype=object)

`map` funksiyasi

In [70]:
del df['county']

In [71]:
df.dropna(inplace=True)

In [74]:
df['driver_age_raw'] = df['driver_age_raw'].map(lambda x: round(x))

In [75]:
df['driver_age_raw']

24       1979
40       1988
41       1988
80       1975
106      1978
         ...
91494    1966
91548    1986
91672    1996
91700    1987
91708    1992
Name: driver_age_raw, Length: 3193, dtype: int64

In [76]:
df['driver_age'] = df['driver_age'].map(lambda x: int(x))

In [77]:
df.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related
24,8/28/2005,1:00,Erkak,1979,26,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False
40,10/1/2005,0:00,Erkak,1988,17,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,16-30 Min,True
41,10/1/2005,0:00,Erkak,1988,17,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,30+ Min,True
80,10/2/2005,9:30,Erkak,1975,30,White,Speeding,Speeding,True,Incident to Arrest,Arrest Driver,True,30+ Min,False
106,10/3/2005,14:00,Erkak,1978,27,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,16-30 Min,False

In [78]:
df['driver_age'].dtype

dtype('int64')

In [86]:
df['driver_age'] = df['driver_age'].astype(np.float64)

In [87]:
df.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related
24,8/28/2005,1:00,Erkak,1979,26.0,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False
40,10/1/2005,0:00,Erkak,1988,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,16-30 Min,True
41,10/1/2005,0:00,Erkak,1988,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,30+ Min,True
80,10/2/2005,9:30,Erkak,1975,30.0,White,Speeding,Speeding,True,Incident to Arrest,Arrest Driver,True,30+ Min,False
106,10/3/2005,14:00,Erkak,1978,27.0,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,16-30 Min,False

In [88]:
df.replace([True, False], [1, 0], inplace=True)

In [89]:
df.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related
24,8/28/2005,1:00,Erkak,1979,26.0,White,Other Traffic Violation,Moving violation,1,"Incident to Arrest,Protective Frisk",Arrest Driver,1,16-30 Min,0
40,10/1/2005,0:00,Erkak,1988,17.0,White,Equipment/Inspection Violation,Equipment,1,Probable Cause,Arrest Driver,1,16-30 Min,1
41,10/1/2005,0:00,Erkak,1988,17.0,White,Equipment/Inspection Violation,Equipment,1,Probable Cause,Citation,0,30+ Min,1
80,10/2/2005,9:30,Erkak,1975,30.0,White,Speeding,Speeding,1,Incident to Arrest,Arrest Driver,1,30+ Min,0
106,10/3/2005,14:00,Erkak,1978,27.0,Black,Equipment/Inspection Violation,Equipment,1,Probable Cause,Citation,0,16-30 Min,0

In [92]:
df['is_arrested'].value_counts()

is_arrested
0    2100
1    1093
Name: count, dtype: int64

`applymap()` va `apply()` funksiyalari